import { compare } from './calculator.js';
import { clearUI, readProducts, renderProducts, showResults, toast } from './ui.js';
const template = /** @type {HTMLTemplateElement} */ (document.querySelector('#product-template'));
const form = /** @type {HTMLFormElement} */ (document.querySelector('#comparator'));
const dialog = /** @type {HTMLDialogElement} */ (document.querySelector('#confirm-reset'));
renderProducts(template);
form.addEventListener('submit', event => { event.preventDefault(); if (!showResults(compare(readProducts()))) form.querySelector(':invalid, .price')?.focus(); });
document.querySelector('#reset').addEventListener('click', () => dialog.showModal());
document.querySelector('#cancel-reset').addEventListener('click', () => dialog.close());
document.querySelector('#confirm-reset-button').addEventListener('click', () => { clearUI(); dialog.close(); toast('All fields cleared.'); document.querySelector('.name').focus(); });
dialog.addEventListener('click', event => { if (event.target === dialog) dialog.close(); });
document.querySelector('#try-example').addEventListener('click', () => { const example=[['Family box','5.49','18','oz'],['Value box','6.29','650','g'],['Small box','3.79','12','oz']]; clearUI(); document.querySelectorAll('.product').forEach((card,index)=>{const [name,price,quantity,unit]=example[index]; card.querySelector('.name').value=name; card.querySelector('.price').value=price; card.querySelector('.quantity').value=quantity; card.querySelector('.unit').value=unit;}); toast('Example loaded — compare the cereal boxes.'); });
