import{validateDraft}from'./core.ts';import{CandleStore}from'./storage.ts';import type{Candle}from'./types.ts';import{CandleView}from'./view.ts';
const id=()=>typeof crypto.randomUUID==='function'?crypto.randomUUID():`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
class CandleController{
 private candles:Candle[]=[];constructor(private store:CandleStore,private view:CandleView){}
 start():void{const loaded=this.store.load();this.candles=loaded.value;if(!loaded.ok)this.view.showPersistent(loaded.error);this.view.form.addEventListener('input',()=>this.preview());this.view.form.addEventListener('change',()=>{this.view.syncUnit();this.preview()});this.view.form.addEventListener('submit',e=>this.save(e));this.view.list.addEventListener('click',e=>void this.remove(e));document.querySelector('#empty-action')?.addEventListener('click',()=>this.view.focusForm());this.view.render(this.candles);this.view.syncUnit();this.preview();setTimeout(()=>this.view.finishLoading(),matchMedia('(prefers-reduced-motion: reduce)').matches?0:180)}
 private preview():void{const draft=this.view.readDraft(),saveable=validateDraft(draft).ok,r=validateDraft(draft,false);this.view.showEstimate(r,saveable);if(r.ok)this.view.clearError()}
 private save(e:SubmitEvent):void{e.preventDefault();const r=validateDraft(this.view.readDraft());if(!r.ok){this.view.showError(r.error);document.querySelector<HTMLElement>(`[name="${r.field}"]`)?.focus();return}const candle:Candle={...r.value,id:id(),createdAt:new Date().toISOString()},before=this.candles;this.candles=[candle,...before];const saved=this.store.save(this.candles);if(!saved.ok){this.candles=before;this.view.showError(saved.error);this.view.showPersistent(saved.error)}else{this.view.clearPersistent();this.view.reset();this.view.showToast(`${candle.name} saved to your shelf.`)}this.view.render(this.candles)}
 private async remove(e:Event):Promise<void>{const button=(e.target as Element).closest<HTMLButtonElement>('[data-delete]');if(!button)return;const candle=this.candles.find(c=>c.id===button.dataset.delete);if(!candle){this.view.showPersistent('That candle is no longer in your collection.');return}if(!await this.view.confirmDelete(candle)){button.focus();return}const before=this.candles;this.candles=this.candles.filter(c=>c.id!==candle.id);const saved=this.store.save(this.candles);if(!saved.ok){this.candles=before;this.view.showPersistent(`Candle not removed. ${saved.error}`)}else{this.view.clearPersistent();this.view.showToast(`${candle.name} removed.`)}this.view.render(this.candles)}
}
try{new CandleController(new CandleStore(localStorage),new CandleView()).start()}catch(e){document.body.innerHTML='<main class="fatal"><p class="eyebrow">The flame went out</p><h1>Ember could not open.</h1><p>Reload to try again. Saved candles have not changed.</p></main>';console.error(e)}
