import {formToSouvenir, isSouvenir, selectEntries} from './data.js';
import {loadEntries, saveEntries} from './storage.js';
import {renderGrid, renderSummary, showState} from './render.js';

const state = {entries: [], filter: 'all', mood: 'all', search: '', sort: 'date-desc', view: 'grid', editingId: null};
const $ = selector => document.querySelector(selector);
function toast(message, kind = 'info') { const item = document.createElement('div'); item.className = `toast ${kind}`; const text = document.createElement('span'); text.textContent = message; const close = document.createElement('button'); close.type = 'button'; close.textContent = 'x'; close.setAttribute('aria-label', 'Dismiss message'); close.onclick = () => item.remove(); item.append(text, close); $('#toast-region').append(item); if (kind !== 'error') setTimeout(() => item.remove(), 5000); }
function refresh() { const visible = selectEntries(state.entries, state.filter, state.search, state.sort, state.mood); renderSummary(state.entries, visible.length); renderGrid(visible); const filteredOut = !visible.length && state.entries.length; $('#empty h3').textContent = filteredOut ? 'No matching souvenirs' : 'No souvenirs here yet'; $('#empty p').textContent = filteredOut ? 'Try clearing a filter or searching for something else.' : 'Every trip has a small treasure waiting to be remembered.'; showState(!visible.length); $('#grid').classList.toggle('list-view', state.view === 'list'); const narrowed = state.filter !== 'all' || state.mood !== 'all' || state.search; $('#clear-filters').hidden = !narrowed; $('#collection-meta').textContent = narrowed ? `Showing ${visible.length} of ${state.entries.length} saved memories` : 'Showing every saved memory'; }
function announceSave(message, error = false) { $('#save-status').textContent = message; $('#save-status').classList.toggle('error', error); }
function setFormMode(editing) { $('#form-eyebrow').textContent = editing ? 'EDIT ENTRY' : 'NEW ENTRY'; $('#add-title').innerHTML = editing ? 'Refine the<br /><em>memory</em>.' : 'Add a little<br /><em>evidence</em> of the trip.'; $('#form-submit').innerHTML = editing ? 'Update logbook <span>\u2192</span>' : 'Save to logbook <span>\u2192</span>'; $('#cancel-edit').hidden = !editing; }
function beginEdit(entry) { state.editingId = entry.id; const form = $('#souvenir-form'); Object.entries({name:entry.name, description:entry.description, city:entry.city, country:entry.country, date:entry.date, category:entry.category, memory:entry.memory}).forEach(([key, value]) => { form.elements[key].value = value; }); const mood = form.querySelector(`[name="mood"][value="${entry.mood}"]`); if (mood) mood.checked = true; setFormMode(true); $('#add').scrollIntoView({behavior:'smooth'}); $('#item-name').focus(); }
function endEdit() { state.editingId = null; $('#souvenir-form').reset(); $('#date').value = new Date().toISOString().slice(0,10); setFormMode(false); $('#form-error').textContent = ''; }
function exportCollection() { const blob = new Blob([JSON.stringify(state.entries, null, 2)], {type:'application/json'}); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `sunburn-summits-${new Date().toISOString().slice(0,10)}.json`; document.body.append(link); link.click(); setTimeout(() => { URL.revokeObjectURL(link.href); link.remove(); }, 100); toast('Backup downloaded', 'success'); }
async function importCollection(file) { try { const parsed = JSON.parse(await file.text()); if (!Array.isArray(parsed) || parsed.some(entry => !isSouvenir(entry))) throw new Error('invalid backup'); const saved = saveEntries(parsed); if (!saved.ok) throw new Error(saved.error); state.entries = parsed; endEdit(); refresh(); announceSave('Imported just now'); toast(`${parsed.length} memories restored`, 'success'); } catch (error) { toast(error.message === 'invalid backup' ? 'That file is not a valid Sunburn & Summits backup.' : 'The backup could not be imported.', 'error'); } }
function init() {
  const form = $('#souvenir-form'); form.autocomplete = 'off'; $('.composer .eyebrow').id = 'form-eyebrow'; $('#collection-title').tabIndex = -1; const submit = form.querySelector('.submit-button'); submit.id = 'form-submit'; const cancel = document.createElement('button'); cancel.type = 'button'; cancel.id = 'cancel-edit'; cancel.className = 'cancel-edit'; cancel.textContent = 'Cancel editing'; cancel.hidden = true; submit.before(cancel); cancel.onclick = endEdit;
  $('#loading').hidden = false;
  try { const loaded = loadEntries(); state.entries = loaded.entries || []; $('#loading').hidden = true; refresh(); if (loaded.error) { toast(loaded.error, 'error'); announceSave('Storage needs attention', true); } } catch (error) { $('#loading').hidden = true; toast('The logbook could not open. Please reload and try again.', 'error'); announceSave('Unable to open logbook', true); console.error(error); }
  document.querySelectorAll('[data-filter]').forEach(button => button.addEventListener('click', () => { state.filter = button.dataset.filter; document.querySelectorAll('[data-filter]').forEach(b => { const active = b === button; b.classList.toggle('active', active); b.setAttribute('aria-pressed', active); }); refresh(); }));
  $('#search').addEventListener('input', e => { state.search = e.target.value; refresh(); }); $('#sort').addEventListener('change', e => { state.sort = e.target.value; refresh(); }); $('#mood-filter').addEventListener('change', e => { state.mood = e.target.value; refresh(); });
  $('#clear-filters').onclick = () => { state.filter = 'all'; state.mood = 'all'; state.search = ''; $('#search').value = ''; $('#mood-filter').value = 'all'; document.querySelectorAll('[data-filter]').forEach(b => { b.classList.toggle('active', b.dataset.filter === 'all'); b.setAttribute('aria-pressed', b.dataset.filter === 'all'); }); refresh(); };
  $('#export-data').onclick = exportCollection; $('#import-data').onclick = () => $('#import-file').click(); $('#import-file').addEventListener('change', e => { if (e.target.files[0]) importCollection(e.target.files[0]); e.target.value = ''; });
  document.querySelectorAll('[data-view]').forEach(button => button.onclick = () => { state.view = button.dataset.view; document.querySelectorAll('[data-view]').forEach(b => { const active = b === button; b.classList.toggle('active', active); b.setAttribute('aria-pressed', active); }); refresh(); });
  form.addEventListener('submit', e => { e.preventDefault(); const result = formToSouvenir(form); $('#form-error').textContent = result.error || ''; if (!result.value) { [...form.elements].find(field => field.required && !field.value.trim())?.focus(); return; } const wasEditing = Boolean(state.editingId); const next = wasEditing ? state.entries.map(x => x.id === state.editingId ? {...result.value, id: state.editingId} : x) : [result.value, ...state.entries]; const saved = saveEntries(next); if (!saved.ok) { $('#form-error').textContent = saved.error; toast(saved.error, 'error'); announceSave('Not saved - storage error', true); return; } state.entries = next; endEdit(); announceSave('Saved just now'); toast(wasEditing ? 'Souvenir updated' : 'Souvenir added to your logbook', 'success'); refresh(); $('#collection').scrollIntoView({behavior:'smooth'}); });
  const dialog = $('#delete-dialog'); $('#grid').addEventListener('click', e => { const edit = e.target.closest('[data-edit]'); if (edit) { const entry = state.entries.find(x => x.id === edit.dataset.edit); if (entry) beginEdit(entry); return; } const remove = e.target.closest('[data-delete]'); if (!remove) return; dialog.dataset.pending = remove.dataset.delete; dialog.returnFocus = remove; dialog.showModal(); });
  dialog.addEventListener('click', e => { if (e.target.matches('[value="cancel"]')) { dialog.close(); return; } if (!e.target.matches('[value="confirm"]')) return; const next = state.entries.filter(x => x.id !== dialog.dataset.pending); const saved = saveEntries(next); if (!saved.ok) { toast(saved.error, 'error'); announceSave('Not saved - storage error', true); return; } state.entries = next; dialog.close(); announceSave('Saved just now'); toast('Souvenir removed', 'success'); refresh(); });
  dialog.addEventListener('close', () => { const target = dialog.returnFocus; delete dialog.returnFocus; delete dialog.dataset.pending; if (target?.isConnected) target.focus(); else $('#collection-title').focus(); });
  window.addEventListener('error', event => { console.error(event.error || event.message); toast('Something went wrong while updating the logbook. Please try again.', 'error'); }); window.addEventListener('unhandledrejection', event => { console.error(event.reason); toast('An unexpected operation failed. Your saved entries are unchanged.', 'error'); });
  $('#date').value = new Date().toISOString().slice(0,10);
}
init();
