import{formatDuration,formatWeight,resultMessage}from'./core.ts';import type{Candle,CandleDraft,EstimateResult}from'./types.ts';
const get=<T extends Element>(s:string):T=>{const n=document.querySelector<T>(s);if(!n)throw Error(`Missing interface element: ${s}`);return n};
const make=<K extends keyof HTMLElementTagNameMap>(tag:K,text='',cls=''):HTMLElementTagNameMap[K]=>{const n=document.createElement(tag);n.textContent=text;n.className=cls;return n};
export class CandleView{
 readonly form=get<HTMLFormElement>('#candle-form');readonly list=get<HTMLElement>('#candle-list');readonly dialog=get<HTMLDialogElement>('#delete-dialog');private timer?:number;
 readDraft():CandleDraft{const d=new FormData(this.form);return{name:String(d.get('name')??''),weight:String(d.get('weight')??''),unit:String(d.get('unit')??''),wicks:String(d.get('wicks')??''),diameter:String(d.get('diameter')??'')}}
 showEstimate(r:EstimateResult):void{get<HTMLButtonElement>('#save-button').disabled=!r.ok;get('#result').classList.toggle('is-ready',r.ok);get('#result-time').textContent=r.ok?formatDuration(r.value.burnMinutes):'—';get('#result-copy').textContent=r.ok?resultMessage(r.value.burnMinutes):'Complete the details to see your estimate.'}
 render(items:Candle[]):void{this.list.replaceChildren(...items.map((c,i)=>this.card(c,i)));this.list.hidden=!items.length;get('#empty-state').toggleAttribute('hidden',!!items.length);get('#saved-count').textContent=String(items.length).padStart(2,'0');get('#collection-summary').textContent=items.length?`${items.length} ${items.length===1?'candle':'candles'}, ordered by newest.`:'Your collection lives only in this browser.'}
 finishLoading():void{get<HTMLElement>('#loader').hidden=true;get('.collection').setAttribute('aria-busy','false')}
 showError(v:string):void{get('#form-error').textContent=v}clearError():void{this.showError('')}
 showPersistent(v:string):void{const n=get<HTMLElement>('#persistent-status');n.textContent=v;n.hidden=false}clearPersistent():void{get<HTMLElement>('#persistent-status').hidden=true}
 reset():void{this.form.reset();this.clearError();this.showEstimate({ok:false,field:'name',error:''})}
 focusForm():void{get<HTMLInputElement>('#name').focus();get('#estimator-title').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
 showToast(v:string):void{const n=get<HTMLElement>('#toast');window.clearTimeout(this.timer);n.textContent=v;n.hidden=false;this.timer=window.setTimeout(()=>n.hidden=true,3600)}
 confirmDelete(c:Candle):Promise<boolean>{get('#dialog-copy').textContent=`${c.name} (${formatWeight(c)}, ${c.wicks} ${c.wicks===1?'wick':'wicks'}, ${c.diameter} in) will be removed from this browser.`;this.dialog.returnValue='';this.dialog.showModal();return new Promise(resolve=>this.dialog.addEventListener('close',()=>resolve(this.dialog.returnValue==='confirm'),{once:true}))}
 private card(c:Candle,i:number):HTMLElement{const a=make('article','','candle-item');a.style.setProperty('--i',String(Math.min(i,8)));const main=make('div'),name=make('h3',c.name),specs=make('p',`${formatWeight(c)} · ${c.wicks} ${c.wicks===1?'wick':'wicks'} · ${c.diameter} in diameter`),time=make('p','','item-duration');time.innerHTML=`<span>Estimated</span><strong>${formatDuration(c.burnMinutes)}</strong>`;const remove=make('button','Remove');remove.type='button';remove.dataset.delete=c.id;remove.setAttribute('aria-label',`Remove ${c.name}`);main.append(name,specs);a.append(main,time,remove);return a}
}
